#NAME "Basic dictionary for tests"
#INDEX_LANGUAGE "English"
#CONTENTS_LANGUAGE "Russian"

automatic
	\[[t]ˌɔːtə'mætɪk[/t]\] [p]брит.[/p] [s]automatic.wav[/s] / [p]амер.[/p] [s]943.wav[/s]
	[m1][b]1.[/b] [p]прил.[/p][/m]
	[m1]1) [trn]автоматический, автоматизированный[/trn][/m]
	[m2][*]- [ref]automatic pistol[/ref][/*][/m]
	[m2][*]- [ref]automatic rifleman[/ref][/*][/m]
	[m2][*]- [ref]automatic stoker[/ref][/*][/m]
	[m2][*]- [ref]automatic telephone exchange[/ref][/*][/m]
	[m2][*]- [ref]automatic transmitter[/ref][/*][/m]
	[m2][*]- [ref]automatic weapon[/ref][/*][/m]
	[m1]2) [trn]машинальный, непроизвольный[/trn][/m]
	[m2][*][ex][lang id=1033]The winking of the eyes is essentially automatic.[/lang] — Глаза моргают непроизвольно.[/ex][/*][/m]
	[m2][*][b]Syn:[/b][/*][/m]
	[m2][*][ref]mechanical[/ref], [ref]perfunctory[/ref][/*][/m]
	[m1][b]2.[/b] [p]сущ.[/p][/m]
	[m1]1) [trn]автоматическое устройство; автомат[/trn][/m]
	[m2][*][ex][lang id=1033]Failures of the automatics may be more dangerous than the human failures they are designed to prevent.[/lang] — Ошибки автоматов могут быть более опасными, чем человеческие ошибки, которые эти устройства должны предотвращать.[/ex][/*][/m]
	[m1]2) [trn]автоматическое оружие[/trn][/m]
	[m1]3) [trn]автомобиль с автоматической коробкой передач[/trn][/m]
extra
	\[[t]'ekstrə[/t]\][p][i]брит.[/i][/p] [s]extra.wav[/s] / [p][i]амер.[/i][/p] [s]4685.wav[/s]
	[m1][trn]дополнительный; дополнительно; особо; добавочный; экстра; статист; экстренный[/trn][/m]
money
	\[[t]'mʌnɪ[/t]\] [p]брит.[/p] [s]money.wav[/s] / [p]амер.[/p] [s]8252.wav[/s]
	[p]сущ.[/p][c];[/c] [p]мн.[/p] [c]moneys, monies[/c]
	[m1]1)[/m]
	[m2]а) [p][trn]употр. с гл. в ед.[/p] деньги[/trn][/m]
	[m3][*][ex][lang id=1033]for money[/lang] — за деньги[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to do smth. for money[/lang] — делать что-л. за деньги[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to borrow money[/lang] — занимать деньги[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to change money[/lang] — менять деньги[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to counterfeit money[/lang] — подделывать деньги[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to earn / make money[/lang] — делать, зарабатывать, наживать деньги[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to lend money[/lang] — одалживать деньги[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to produce money[/lang] — чеканить, выпускать деньги[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to save money[/lang] — копить, экономить деньги[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to spend money[/lang] — тратить деньги[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to squander / throw away money[/lang] — швыряться деньгами, выбрасывать деньги на ветер[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to withdraw money[/lang] — изымать деньги [i][com](из обращения)[/com][/ex][/i][/*][/m]
	[m3][*][ex][lang id=1033]to sink (a lot of) money into (a venture)[/lang] — вложить (много) денег в (предприятие)[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to launder (illegally acquired) money[/lang] — отмывать (чёрные) деньги[/ex][/*][/m]
	[m3][*][ex][lang id=1033]They invested their money in stocks and bonds.[/lang] — Они вложили деньги в государственные ценные бумаги и боны.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]We are out of money.[/lang] — У нас нет денег.[/ex][/*][/m]
	[m3][*]- [ref]black money[/ref][/*][/m]
	[m3][*]- [ref]blood money[/ref][/*][/m]
	[m3][*]- [ref]conscience money[/ref][/*][/m]
	[m3][*]- [ref]counterfeit money[/ref][/*][/m]
	[m3][*]- [ref]earnest money[/ref][/*][/m]
	[m3][*]- [ref]easy money[/ref][/*][/m]
	[m3][*]- [ref]hush money[/ref][/*][/m]
	[m3][*]- [ref]overnight money[/ref][/*][/m]
	[m3][*]- [ref]paper money[/ref][/*][/m]
	[m3][*]- [ref]money belt[/ref][/*][/m]
	[m3][*]- [ref]pocket money[/ref][/*][/m]
	[m3][*]- [ref]prize money[/ref][/*][/m]
	[m3][*]- [ref]seed money[/ref][/*][/m]
	[m3][*]- [ref]silly money[/ref][/*][/m]
	[m3][*]- [ref]tax money[/ref][/*][/m]
	[m3][*]- [ref]tight money[/ref][/*][/m]
	[m3][*]- [ref]upfront money[/ref][/*][/m]
	[m3][*]- [ref]well-spent money[/ref][/*][/m]
	[m3][*]- [ref]bank money[/ref][/*][/m]
	[m3][*]- [ref]circulate money[/ref][/*][/m]
	[m3][*]- [ref]deposit money[/ref][/*][/m]
	[m3][*]- [ref]invest money in smth.[/ref][/*][/m]
	[m3][*]- [ref]put money into smth.[/ref][/*][/m]
	[m3][*]- [ref]put up money[/ref][/*][/m]
	[m3][*]- [ref]put money on smth.[/ref][/*][/m]
	[m3][*]- [ref]raise money[/ref][/*][/m]
	[m3][*]- [ref]refund money[/ref][/*][/m]
	[m3][*]- [ref]return money[/ref][/*][/m]
	[m3][*]- [ref]tie up money[/ref][/*][/m]
	[m2]б) [trn]платёжное средство[/trn][/m]
	[m3][*][b]Syn:[/b][/*][/m]
	[m3][*][ref]circulating medium[/ref][/*][/m]
	[m2]в) [trn]богатство; собственность[/trn][/m]
	[m3][*]- [ref]in the money[/ref][/*][/m]
	[m1]2) [trn]национальная валюта[/trn][/m]
	[m1]3) [i][trn][com](monies)[/com][/i] [p]юр.[/p] денежные суммы[/trn][/m]
	[m1][*]•[/*][/m]
	[m1][*][ex][lang id=1033]He has money to burn.[/lang] — У него денег куры не клюют.[/ex][/*][/m]
	[m1][*][ex][lang id=1033]Money makes money.[/lang] [p]посл.[/p] — Деньги к деньгам.[/ex][/*][/m]
	[m1]- [ref]old money[/ref][/m]
	[m1]- [ref]money for old rope[/ref][/m]
	[m1]- [ref]mad money[/ref][/m]
	[m1]- [ref]money laundering[/ref][/m]
	[m1]- [ref]on the money[/ref][/m]
province
	\[[t]'prɒvɪns[/t]\] [s]province.wav[/s]
	[m1][p]n[/p][/m]
	[m1]1) [trn]пров[']и[/']нция [com]([i]единица административного деления[/i])[/com][/trn][/m]
	[m2][*][ex][lang id=1033]the Province of Alberta in Canada[/lang] — пров[']и[/']нция Альб[']е[/']рта в Кан[']а[/']де[/ex][/*][/m]
	[m1]2) [p][trn]pl[/p] пров[']и[/']нция, перифер[']и[/']я[/trn][/m]
	[m2][*][ex][lang id=1033]life in the provinces[/lang] — жизнь в пров[']и[/']нции[/ex][/*][/m]
	[m1]3) [trn]компет[']е[/']нция[/trn][/m]
	[m2][*][ex][lang id=1033]to be outside smb's province[/lang] — не вход[']и[/']ть в чью-л. компет[']е[/']нцию[/ex][/*][/m]
	[m2][*][ex][lang id=1033]to be smb's province[/lang] — относ[']и[/']ться к сф[']е[/']ре д[']е[/']ятельности ког[']о[/']-л.[/ex][/*][/m]
	[m2][*][ex][lang id=1033]to remain the province of specialists[/lang] — вход[']и[/']ть в компет[']е[/']нцию специал[']и[/']стов[/ex][/*][/m]